### ISSUE TITLE
Ready for D8?

### ISSUE THREAD

**Issue by aries1980** [Gizra/message_notify#42]
Hi there,

Is the module ready to use for Drupal 8.x?
I enabled the module, set the default notifier to “Email”, made some stuff that created Message entities, but nothing happened. Checked the source code, but I can't see where it hooks up on the entity creation. If I enable the module, should it do what I want to do or I miss something?

Thanks,
Janos

**Comment by jhedstrom** [comment]
Hi Janos,

It is indeed ready for Drupal 8. However, just as it was in Drupal 7, this is mostly an API.In short, the hook-ups to entity creation/updates need to be implemented manually (this is in order to provide maximum flexibility).  There is the message_examples module that is part of the message repo, I don't think that is fully ported, but may still provide guidance for getting started. There are also the [Drupal 7 docs](https://www.drupal.org/node/2180145).

**Comment by aries1980** [comment]
Hi @jhedstrom ,

I'm checking the 8.x version of message_notify_test module , but it is relatively empty compared to the 7.x version. I see in the 7.x there is a message_notify_send_message() , but not for the 8.x . The 8.x just pulls in an empty plugin. Can you write me a short snippet please how can I trigger the sending? Thank you!

**Comment by aries1980** [comment]
Ok, I found it out:

```
$message = \Drupal\message\Entity\Message::load(1234);
$outcome = \Drupal::service('message_notify.sender')->send($message, [], 'email');
```

The problem is, it converts it to plaint text email, instead of a HTML-one, multi-part email. Do I do something wrong?

**Comment by aries1980** [comment]
Ok, I close this ticket because the original scope (the emails weren't sent out) has been answer. Thanks!
